apiVersion: apps/v1
kind: Deployment
metadata:
   name: appid-sample-deployment
   namespace: kube-public
   labels:
    app: appid-sample
spec:
   revisionHistoryLimit: 10
   minReadySeconds: 10
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 0
         maxSurge: 3
   replicas: 1
   selector:
    matchLabels:
      app: appid-sample
   template:
      metadata:
         labels:
            microservice: appid-sample
            app: appid-sample
      spec:
         containers:
         - name: appid-sample
           image: "italo1silva/public:1" # <-- edit here
           ports:
           - containerPort: 80
           env:
           - name: redirectUri
             value: "169.51.204.237:30000/ibm/cloud/appid/callback" # <-- edit here
           - name: APPID_SERVICE_BINDING
             valueFrom:
               secretKeyRef:
                 name: binding-vir # <-- edit here
                 key: binding
---
apiVersion: v1
kind: Service
metadata:
  name: appid-sample-service
spec:
  selector:
    microservice: appid-sample
  type: NodePort
  ports:
   - port: 80
     nodePort: 30000
     # In an IBM Cloud Container Service Lite Cluster, we have to create the services with Node ports that have non standard ports in the 30000-32767 range.